"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(n):
    if n < 3: return n
    return fibonacci(n - 1) + fibonacci(n - 2)

value = 0
sum_of_even_terms = 0
n = 1

while value <= 4e6:
    value = fibonacci(n)
    if value % 2 == 0:
        sum_of_even_terms += value
    n += 1
    
print(sum_of_even_terms)
